DL_app/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth.views import auth_login
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = "DL_app"

urlpatterns = [
    path('', views.main, name='main'),
    path('courses/', views.courses, name='courses'),
    path('student_attendance/<int:course_id>/', views.student_attendance, name='student_attendance'),
    path('student_scores/<int:course_id>/', views.student_scores, name='student_scores'),
    path('course_user/<int:course_id>/', views.course_user, name='course_user'),
    path('task_user/<int:task_id>/', views.task_user, name='task_user'),
    path('login', auth_login, name="login"),
    url(r'^media/(?P<path>.*)$', views.download),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Project_DL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DL_app.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DL_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.


class SimpleUser(AbstractUser):
    user_role = models.TextField()
    user_group = models.TextField()

    def __str__(self):
        return self.username


# class User(models.Model):
#     user_id = models.CharField(max_length=9999)
#     user_password = models.TextField(default='123456')
#     user_name = models.TextField()
#     user_surname = models.TextField()
#     user_date_of_birth = models.DateField('date of birth')
#     user_role = models.TextField()


class Group(models.Model):
    group_id = models.CharField(max_length=9999)
    group_name = models.TextField()
    group_curator = models.TextField()


class Course(models.Model):
    course_id = models.CharField(max_length=9999)
    course_name = models.TextField()
    course_teacher = models.TextField()


class GroupCourse(models.Model):
    group_id = models.TextField()
    course_id = models.TextField()
    semester = models.TextField()


class TeacherCourses(models.Model):
    teacher_id = models.TextField()
    course_id = models.TextField()


class Tasks(models.Model):
    task_id = models.CharField(max_length=9999)
    course_id = models.TextField()
    task_name = models.TextField()
    task_description = models.TextField()
    task_files = models.FileField(upload_to='uploads/')
    task_deadline = models.DateField()


class UserTask(models.Model):
    student_id = models.TextField()
    task_id = models.TextField()
    score = models.FloatField()
    files = models.FileField()
    time = models.DateField()


class Schedule(models.Model):
    schedule_id = models.TextField()
    schedule_date = models.DateField()
    course_id = models.TextField()
    type = models.TextField()


class UserSchedule(models.Model):
    student_id = models.TextField()
    schedule_id = models.TextField()
    is_was = models.BooleanField()


class News(models.Model):
    news_id = models.CharField(max_length=9999)
    news_author = models.TextField()
    news_title = models.TextField()
    news_content = models.TextField()
    news_date = models.DateTimeField('date')

    def datemonth(self):
        return self.news_date.strftime('%d %B')

DL_app/views.py
import os
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from .models import *
from django.http import HttpResponse



# Create your views here.
def main(request):
    all_news = News.objects.order_by('-news_date')
    return render(request, "DL_app/main.html", {'all_news': all_news})


def login(request):
    return render(request, "DL_app/login.html")


def courses(request):
    username = request.user.username
    user_role = ''
    user_group = ''
    user_id = ''
    group_id = ''
    i = 0
    query = 'SELECT * FROM DL_app_Course'
    for user in SimpleUser.objects.raw('SELECT * FROM DL_app_SimpleUser WHERE username=%s', [username]):
        user_role = user.user_role
    if user_role == "Student":
        for user in SimpleUser.objects.raw('SELECT * FROM DL_app_SimpleUser WHERE username=%s', [username]):
            user_group = user.user_group
        for group in Group.objects.raw('SELECT * FROM DL_app_Group WHERE group_name=%s', [user_group]):
            group_id = group.group_id
        for groupcourse in GroupCourse.objects.raw('SELECT * FROM DL_app_GroupCourse WHERE group_id=%s', [group_id]):
            if i == 0:
                query = query + ' WHERE'
                query = query + ' course_id=' + groupcourse.course_id
            else:
                query = query + ' OR course_id=' + groupcourse.course_id
            i = i + 1
    elif user_role == "Teacher":
        for user in SimpleUser.objects.raw('SELECT * FROM DL_app_SimpleUser WHERE username=%s', [username]):
            user_id = user.id
        for groupcourse in TeacherCourses.objects.raw('SELECT * FROM DL_app_TeacherCourses WHERE teacher_id=%s', [user_id]):
            if i == 0:
                query = query + ' WHERE'
                query = query + ' course_id=' + groupcourse.course_id
            else:
                query = query + ' OR course_id=' + groupcourse.course_id
            i = i + 1
    all_course = Course.objects.raw(query)
    return render(request, "DL_app/courses.html", {'all_course': all_course})


def course_user(request, course_id):
    course_art = get_object_or_404(Course, pk=course_id)
    all_tasks = Tasks.objects.filter(course_id=course_id)
    return render(request, "DL_app/course_user.html", {"all_tasks": all_tasks, "course": course_art})


def task_user(request, task_id):
    task_art = get_object_or_404(Tasks, pk=task_id)
    return render(request, "DL_app/task_user.html", {"tasks": task_art})


def student_attendance(request, course_id):
    course_art = get_object_or_404(Course, pk=course_id)
    return render(request, "DL_app/attendance_student.html", {"course": course_art})


def student_scores(request, course_id):
    course_art = get_object_or_404(Course, pk=course_id)
    return render(request, "DL_app/score_student.html", {"course": course_art})

def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/octet-stream")
            response['Content-Disposition'] = 'inline; filename' + os.path.basename(file_path)
            return response

DL_app/templates/DL_app/attendance_student.html
{%extends "DL_app/layout.html" %}

{%block content%}
<div class="card w-100 mb-md-3 shadow-sm">
    <div class="card-body">
        <h4 class="card-title font-weight-bold mb-md-3">Посещаемость ( {{ course.course_name }} ) :</h4>

        <table class="table mt-3">
            <caption>Процент по всем посещенным занятиям : 70,8%<br>Максимальный возможный процент : 75,9%</caption>
            <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Дата</th>
                <th scope="col">Описание</th>
                <th class="text-md-center" scope="col">Статус</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">1</th>
                <td>4/11/19 (Пн)<br />11AM - 1PM</td>
                <td>Лекция</td>
                <td class="text-md-center">Был</td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>11/11/19 (Пн)<br />11AM - 1PM</td>
                <td>Практика</td>
                <td class="text-md-center">Не был</td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td>18/11/19 (Пн)<br />11AM - 1PM</td>
                <td>Лекция</td>
                <td class="text-md-center">Был</td>
            </tr>
            <tr>
                <th scope="row">4</th>
                <td>25/11/19 (Пн)<br />11AM - 1PM</td>
                <td>Практика</td>
                <td class="text-md-center">Не был</td>
            </tr>
            <tr>
                <th scope="row">5</th>
                <td>2/12/19 (Пн)<br />11AM - 1PM</td>
                <td>Лекция</td>
                <td class="text-md-center">Был</td>
            </tr>
            <tr>
                <th scope="row">6</th>
                <td>9/12/19 (Пн)<br />11AM - 1PM</td>
                <td>Практика</td>
                <td class="text-md-center">Был</td>
            </tr>
            <tr>
                <th scope="row">7</th>
                <td>16/12/19 (Пн)<br />11AM - 1PM</td>
                <td>Лекция</td>
                <td class="text-md-center">Был</td>
            </tr>
            <tr>
                <th scope="row">8</th>
                <td>16/12/19 (Пн)<br />11AM - 1PM</td>
                <td>Практика</td>
                <td class="text-md-center">Был</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
{%endblock%}

DL_app/templates/DL_app/course_user.html
{%extends "DL_app/layout.html" %}

{%block content%}
<div class="row mt-md-3">
    <div class="col-md-10">
        <div class="card w-100 mb-md-3 shadow-sm">
            <div class="card-body">
                <h4 class="card-title font-weight-bold mb-md-3">{{ course.course_name }} :</h4>

                <div class="card w-100 mb-md-3">
                    <div class="card-body">
                        <ul>
                            {% for task in all_tasks %}
                            <li>
                                <a class="text-decoration-none" href="{% url 'DL_app:task_user' task.task_id %}">{{ task.task_name }} </a>
                            </li>
                            {%endfor%}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}

DL_app/templates/DL_app/courses.html
{%extends "DL_app/layout.html" %}

{%block content%}
{% if user.user_role == "Student" %}
    <div class="row">
        <div class="col-md-10">
            <div class="card w-100 h-100 shadow-sm ">
                <div class="card-header h5">
                    Студент
                </div>
                <div class="card-body">
                    <div class="float-md-left">
                        <h5 class="card-title">{{user.first_name}} {{user.last_name}}</h5>
                        <h6 class="card-subtitle text-muted">Имя</h6>
                    </div>
                    <div class="ml-md-5 float-md-left">
                        <h5 class="card-title">{{user.user_group}}</h5>
                        <h6 class="card-subtitle text-muted">Группа</h6>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-2">
            <div class="card w-100 h-100 shadow-sm text-center">
                <div class="card-header h5">
                    GPA
                </div>
                <div class="card-body">
                    <p class="card-text mt-md-2 h4">4</p>
                </div>
            </div>
        </div>
    </div>

    <div class="card w-100 mt-md-3 mb-md-3 shadow-sm">
        <div class="card-body">
            <h4 class="card-title font-weight-bold">Курсы Семестра - 1 :</h4>
            <h6 class="card-subtitle mb-md-4 font-weight-bold">2018/2019</h6>

            {% for course in all_course %}
            <div class="card w-100 mb-md-3">
                <div class="card-body">
                    <h5 class="card-title">{{course.course_name}}</h5>
                    <h6 class="card-subtitle text-muted">Преподаватель <em>{{course.course_teacher}}</em></h6>
                    <hr>
                    <div class="float-left">
                        <a href="{% url 'DL_app:course_user' course.course_id%}" class="card-link">Перейти к курсу</a>
                    </div>
                    <div class="float-right">
                        <a href="{% url 'DL_app:student_scores' course.course_id%}" class="card-link">Оценки</a>
                        <a href="{% url 'DL_app:student_attendance' course.course_id%}" class="card-link">Посещаемость</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% else %}
    <div class="card w-100 mb-md-3 shadow-sm ">
        <div class="card-header h5">
            Преподаватель
        </div>
        <div class="card-body">
            <div class="float-md-left">
                <h5 class="card-title">{{user.first_name}} {{user.last_name}}</h5>
                <h6 class="card-subtitle text-muted">Имя</h6>
            </div>
            <div class="ml-md-5 float-md-left">
                <h5 class="card-title">{{user.user_group}}</h5>
                <h6 class="card-subtitle text-muted">Кафедра</h6>
            </div>
        </div>
    </div>

    <div class="card w-100 mb-md-3 shadow-sm">
        <div class="card-body">
            <h4 class="card-title font-weight-bold mb-md-3">Мои курсы :</h4>

            {% for course in all_course %}
            <div class="card w-100 mb-md-3">
                <div class="card-body">
                    <h5 class="card-title">{{course.course_name}}</h5>
                    <h6 class="card-subtitle text-muted">Весенний семестр 2019</h6>
                    <hr>
                    <div class="float-left mt-md-1">
                        <a href="#" class="card-link">Перейти к курсу</a>
                    </div>
                    <div class="float-right">
                        <button type="button" class="btn btn-sm rounded-0 btn-outline-primary" data-toggle="modal" data-target="#score" data-whatever="@mdo">Оценки</button>
                        <button type="button" class="btn btn-sm rounded-0 btn-outline-primary" data-toggle="modal" data-target="#attendance" data-whatever="@mdo">Посещаемость</button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="modal fade" id="attendance" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ModalLabelAttendance">Посещаемость</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="GroupsAttendance" class="col-form-label">Группа :</label>
                            <select class="custom-select custom-select-sm" id="GroupsAttendance" required>
                                <option value="">CSSE 1815</option>
                                <option value="">CSSE 1814</option>
                                <option value="">CSSE 1813</option>
                                <option value="">IS 1802</option>
                                <option value="">IS 1801</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="datetime" class="col-form-label">Дата :</label>
                            <input type="date" class="form-control form-control-sm" id="datetime" required>
                        </div>

                        <table class="table mt-md-5">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Фамилия</th>
                                <th scope="col">Имя</th>
                                <th class="text-md-center" scope="col">Присутствие</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td>Ахмешев</td>
                                <td>Ринат</td>
                                <td class="text-md-center">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="" id="CheckAttendance1" required>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>Муссин</td>
                                <td>Муса</td>
                                <td class="text-md-center">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="" id="CheckAttendance2" required>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Амир</td>
                                <td>Карина</td>
                                <td class="text-md-center">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="" id="CheckAttendance3" required>
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm rounded-0 btn-outline-secondary" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-sm rounded-0 btn-outline-primary">Сохранить</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="score" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ModalLabelScore">Оценки</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="GroupsScore" class="col-form-label">Группа :</label>
                            <select class="custom-select custom-select-sm" id="GroupsScore" required>
                                <option value="">CSSE 1815</option>
                                <option value="">CSSE 1814</option>
                                <option value="">CSSE 1813</option>
                                <option value="">IS 1802</option>
                                <option value="">IS 1801</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="GroupsScore" class="col-form-label">Задание :</label>
                            <select class="custom-select custom-select-sm" id="TasksScore" required>
                                <option value="">Socket</option>
                                <option value="">Database</option>
                                <option value="">Midterm</option>
                                <option value="">Project</option>
                                <option value="">Endterm</option>
                            </select>
                        </div>

                        <table class="table mt-md-5">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Фамилия</th>
                                <th scope="col">Имя</th>
                                <th class="text-md-center" scope="col">Оценка</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td>Ахмешев</td>
                                <td>Ринат</td>
                                <td class="d-flex justify-content-center">
                                    <input type="text" class="form-control form-control-sm rounded-0 input_h23_w103" id="InputScore1" placeholder="" required>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>Муссин</td>
                                <td>Муса</td>
                                <td class="d-flex justify-content-center">
                                    <input type="text" class="form-control form-control-sm rounded-0 input_h23_w103" id="InputScore2" placeholder="" required>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Амир</td>
                                <td>Карина</td>
                                <td class="d-flex justify-content-center">
                                    <input type="text" class="form-control form-control-sm rounded-0 input_h23_w103" id="InputScore3" placeholder="" required>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm rounded-0 btn-outline-secondary" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-sm rounded-0 btn-outline-primary">Сохранить</button>
                </div>
            </div>
        </div>
    </div>
{% endif %}

{%endblock%}

DL_app/templates/DL_app/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Main</title>

    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'DL_app/css/unauthorized_user_main.css' %}">
</head>
<body>
<div class="container-fluid">
    <nav class="navbar navbar-light bg-white">
        <a class="navbar-brand" href="{% url 'DL_app:main'%}"><h2 class="my-0">DL</h2></a>
        {%block login%}
        {% if user.is_authenticated%}
        <a class="dropdown-toggle text-decoration-none" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{user.first_name}} {{user.last_name}}
        </a>

        <div class="dropdown-menu dropdown-menu-right text-md-center text_fs15" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="#">Профиль</a>
            <a class="dropdown-item" href="{% url 'DL_app:courses'%}">Курсы</a>
            {% if user.user_role == "Student" %}
                <a class="dropdown-item" href="#">Оценки</a>
                <a class="dropdown-item" href="#">Посещаемость</a>
            {% endif %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
        </div>
        {%else%}
        <form class="form-inline">
            <a class="btn btn btn-outline-primary my-2 my-md-0 rounded-0 button_h35_w110" href="{% url 'login'%}">Войти</a>
        </form>
        {%endif%}
        {%endblock%}
    </nav>

    <hr class="hr_mt0_mb0">

    <div class="row mt-md-3">
        <div class="col-md-2">
            <div class="card w-100 shadow-sm mb-md-3">
                <div class="card-body">
                    <h6 class="card-title font-weight-bold">Важные объявления</h6>
                    <hr>
                    <ol class="list-unstyled">
                        <li><a class="text-decoration-none text_fs14" href="login.html">Расписание летнего семестра</a></li>
                        <li><a class="text-decoration-none text_fs14" href="#">Пересдача</a></li>
                        <li><a class="text-decoration-none text_fs14" href="#">Ритейк</a></li>
                        <li><a class="text-decoration-none text_fs14" href="#">HackDay</a></li>
                        <li><a class="text-decoration-none text_fs14" href="#">Хакатон</a></li>
                    </ol>
                </div>
            </div>
            <div class="card w-100 shadow-sm mb-md-3">
                <div class="card-body">
                    <h6 class="card-title font-weight-bold">Преподавателям</h6>
                    <hr>
                    <ol class="list-unstyled">
                        <li><a class="text-decoration-none text_fs14" href="#">Порядок подготовки и проведения экзам.сессии</a></li>
                        <li><a class="text-decoration-none text_fs14" href="#">Система оценивания</a></li>
                        <li><a class="text-decoration-none text_fs14" href="#">План первого семестра</a></li>
                        <li><a class="text-decoration-none text_fs14" href="#">Приказ №890</a></li>
                        <li><a class="text-decoration-none text_fs14" href="#">Приказ №55</a></li>
                    </ol>
                    <h6 class="card-title font-weight-bold mt-md-5">Студентам</h6>
                    <hr>
                    <ol class="list-unstyled">
                        <li><a class="text-decoration-none text_fs14" href="#">Приказ о проведении экзаменационной сессии</a></li>
                        <li><a class="text-decoration-none text_fs14" href="#">Расписание звонков</a></li>
                        <li><a class="text-decoration-none text_fs14" href="#">Приказ №202</a></li>
                        <li><a class="text-decoration-none text_fs14" href="#">Приказ №101</a></li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="col-md-10">
            {% block content %}

            {% endblock %}
        </div>
    </div>

    <footer class="mt-md-5 mb-md-1 text-md-center position-sticky">
        <hr>
        <p>© 2019 Company, Inc.</p>
    </footer>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

DL_app/templates/DL_app/login1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Log In</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/floating-labels/">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% load static %}
    <link href="{% static 'DL_app/css/login.css' %}" rel="stylesheet" type="text/css" >
</head>
<body class="bg-white">
<form class="form-signin" method="post">
    <div class="text-center mb-md-4">
        <h1 class="display-4 mb-md-2">DL</h1>
        <p class="lead">Please sign in</p>
    </div>

    <div class="form-label-group">
        <input type="text" id="inputLogin" class="form-control rounded-0" placeholder="Login" required autofocus>
        <label for="inputLogin">Login</label>
    </div>

    <div class="form-label-group">
        <input type="password" id="inputPassword" class="form-control rounded-0" placeholder="Password" required>
        <label for="inputPassword">Password</label>
    </div>


    <a class="btn btn-lg btn-primary btn-block rounded-0" href="{% url 'DL_app:student_user'%}">Войти</a>

    <hr>

    <p class="mb-md-3 text-muted text-center">© 2019 Company, Inc.</p>
</form>
</body>
</html>

DL_app/templates/DL_app/task_user.html
{%extends "DL_app/layout.html" %}

{%block content%}
        <div class="col-md-10">
            <div class="card w-100 mb-md-3 shadow-sm">
                <div class="card-body">
                    <h4 class="card-title font-weight-bold mb-md-3">Задание :</h4>

                    <div class="card w-100 mb-md-3">
                        <div class="card-body">
                            <h5 class="card-title">{{tasks.task_name}}</h5>
                            <h6 class="card-subtitle text-muted mb-md-3">Срок сдачи : {{tasks.task_deadline}}</h6>
                            <p class="card-text">{{tasks.task_description}}</p>
                            <p class="card-text">When you submit your work, please click on 'submit for the check' button.</p>
                            <a class="card-text" href="{{tasks.task_files.url}}">Скачать</a>
                            <hr>
                            <form>
                                <div class="form-group w-50">
                                    <div class="custom-file form-control-sm">
                                        <input type="file" class="custom-file-input" id="customFile">
                                        <label class="custom-file-label" for="customFile">Выберите файл</label>
                                        <small id="customFileHelpBlock" class="form-text text-muted">
                                            Файл должен быть расширения : .docx, .py, .java, или .zip
                                        </small>
                                    </div>
                                </div>
                                <hr>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-sm rounded-0 btn-outline-primary">Отправить</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{%endblock%}